In [1]:
import requests
import pandas as pd
import os

### Download data

In [2]:
# data path
url = 'https://www.datos.gov.co/resource/yvb2-ppaa.csv'

In [3]:
#  Just run once
# response = requests.get(url)
# print(response)
# response.raise_for_status()

<Response [200]>

In [4]:
path = r'D:\0_Respaldo\0_Proyectos_2024\ML_proyects\tas_interes\data\raw'

In [5]:
filename = os.path.join(path, 'tas.csv')
with open(filename, 'wb') as file:
            file.write(response.content)

### Eda

In [11]:
#csv_file = response
data = pd.read_csv(r'D:\0_Respaldo\0_Proyectos_2024\ML_proyects\tas_interes\data\raw\tas.csv')

In [12]:
data.head(3)

,tipoentidad,codigoentidad,nombreentidad,fechacorte,unidad_de_captura,nombre,tipo,subcuenta,nombre_sub,tasaefectivaanual,montos,num_creditos_desembolsados
0,32,1,Cooperativa Financiera De Antioquia,2019-02-01T00:00:00.000,11,CREDITOS COMERCIALES,ORDINARIO,5,ENTRE 1 Y 30 DIAS,28.34,593975.00,47
1,1,7,Bancolombia,2014-09-26T00:00:00.000,11,CREDITOS COMERCIALES,ORDINARIO,40,A MAS DE 1825 DIAS,11.58,13679369.34,33
2,1,23,Banco De Occidente,2007-05-04T00:00:00.000,9,CREDITOS DE CONSUMO,CREDITOS DE CONSUMO,20,ENTRE 366 Y 1095 DIAS,20.40,3701160.00,0

In [13]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tipoentidad                 1000 non-null   int64
 1   codigoentidad               1000 non-null   int64
 2   nombreentidad               1000 non-null   object
 3   fechacorte                  1000 non-null   object
 4   unidad_de_captura           1000 non-null   int64
 5   nombre                      1000 non-null   object
 6   tipo                        1000 non-null   object
 7   subcuenta                   1000 non-null   int64
 8   nombre_sub                  1000 non-null   object
 9   tasaefectivaanual           1000 non-null   float64
 10  montos                      1000 non-null   float64
 11  num_creditos_desembolsados  1000 non-null   int64
dtypes: float64(2), int64(5), object(5)
memory usage: 93.9+ KB

,tipoentidad,codigoentidad,unidad_de_captura,subcuenta,tasaefectivaanual,montos,num_creditos_desembolsados
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000
mean,3.855000,29.425000,10.935000,40.841000,19.157350,3.654249e+07,4482.598000
std,8.046908,26.139197,1.602293,32.604459,9.037949,2.555763e+08,28073.094678
min,1.000000,1.000000,8.000000,5.000000,0.000000,6.900000e+01,0.000000
25%,1.000000,7.000000,10.000000,15.000000,12.437500,1.214962e+05,0.000000
50%,1.000000,23.000000,11.000000,30.000000,19.610000,7.817313e+05,2.000000
75%,1.000000,44.000000,12.000000,60.000000,26.530000,4.732479e+06,108.250000
max,32.000000,122.000000,16.000000,120.000000,53.040000,4.288410e+09,555930.000000

In [14]:
data.isnull

<bound method DataFrame.isnull of      tipoentidad  codigoentidad                        nombreentidad  \
0             32              1  Cooperativa Financiera De Antioquia
1              1              7                          Bancolombia
2              1             23                   Banco De Occidente
3              1             13                        Bbva Colombia
4              1             34                          Bansuperior
..           ...            ...                                  ...
995            1             30                    Banco Caja Social
996            1              5   Banco Cafetero S.A. En Liquidación
997            1             49                            Av Villas
998            1             14                       Helm Bank S.A.
999            1             39                     Banco Davivienda

                  fechacorte  unidad_de_captura                        nombre  \
0    2019-02-01T00:00:00.000                 11          CREDITOS COMERCIALES
1    2014-09-26T00:00:00.000                 11          CREDITOS COMERCIALES
2    2007-05-04T00:00:00.000                  9           CREDITOS DE CONSUMO
3    2013-05-03T00:00:00.000                 11          CREDITOS COMERCIALES
4    2002-05-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
..                       ...                ...                           ...
995  2021-08-27T00:00:00.000                 11          CREDITOS COMERCIALES
996  2002-11-01T00:00:00.000                 11          CREDITOS COMERCIALES
997  2003-08-15T00:00:00.000                 11          CREDITOS COMERCIALES
998  2012-08-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
999  2012-12-21T00:00:00.000                  9           CREDITOS DE CONSUMO

                                       tipo  subcuenta             nombre_sub  \
0                                 ORDINARIO          5      ENTRE 1 Y 30 DIAS
1                                 ORDINARIO         40     A MAS DE 1825 DIAS
2                       CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS
3                                 ORDINARIO         20  ENTRE 366 Y 1095 DIAS
4    TARJETAS DE CREDITO PERSONAS NATURALES         40     CONS ENT 13 Y 18 M
..                                      ...        ...                    ...
995                               ORDINARIO         20  ENTRE 366 Y 1095 DIAS
996                            DE TESORERIA        110     ENTRE 15 Y 30 DIAS
997                               ORDINARIO         10    ENTRE 31 Y 365 DIAS
998  TARJETAS DE CREDITO PERSONAS NATURALES          5          AVANCES EFECT
999                     CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS

     tasaefectivaanual       montos  num_creditos_desembolsados
0                28.34    593975.00                          47
1                11.58  13679369.34                          33
2                20.40   3701160.00                           0
3                15.23   3850863.00                          50
4                30.50    243807.00                           0
..                 ...          ...                         ...
995              11.27   6676626.30                         102
996               8.61  11176820.00                           0
997              17.02    965000.00                           0
998              30.79   1702206.54                        2563
999              25.14  39049779.38                       13224

[1000 rows x 12 columns]>

In [15]:
data.drop_duplicates
data.dropna

<bound method DataFrame.dropna of      tipoentidad  codigoentidad                        nombreentidad  \
0             32              1  Cooperativa Financiera De Antioquia
1              1              7                          Bancolombia
2              1             23                   Banco De Occidente
3              1             13                        Bbva Colombia
4              1             34                          Bansuperior
..           ...            ...                                  ...
995            1             30                    Banco Caja Social
996            1              5   Banco Cafetero S.A. En Liquidación
997            1             49                            Av Villas
998            1             14                       Helm Bank S.A.
999            1             39                     Banco Davivienda

                  fechacorte  unidad_de_captura                        nombre  \
0    2019-02-01T00:00:00.000                 11          CREDITOS COMERCIALES
1    2014-09-26T00:00:00.000                 11          CREDITOS COMERCIALES
2    2007-05-04T00:00:00.000                  9           CREDITOS DE CONSUMO
3    2013-05-03T00:00:00.000                 11          CREDITOS COMERCIALES
4    2002-05-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
..                       ...                ...                           ...
995  2021-08-27T00:00:00.000                 11          CREDITOS COMERCIALES
996  2002-11-01T00:00:00.000                 11          CREDITOS COMERCIALES
997  2003-08-15T00:00:00.000                 11          CREDITOS COMERCIALES
998  2012-08-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
999  2012-12-21T00:00:00.000                  9           CREDITOS DE CONSUMO

                                       tipo  subcuenta             nombre_sub  \
0                                 ORDINARIO          5      ENTRE 1 Y 30 DIAS
1                                 ORDINARIO         40     A MAS DE 1825 DIAS
2                       CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS
3                                 ORDINARIO         20  ENTRE 366 Y 1095 DIAS
4    TARJETAS DE CREDITO PERSONAS NATURALES         40     CONS ENT 13 Y 18 M
..                                      ...        ...                    ...
995                               ORDINARIO         20  ENTRE 366 Y 1095 DIAS
996                            DE TESORERIA        110     ENTRE 15 Y 30 DIAS
997                               ORDINARIO         10    ENTRE 31 Y 365 DIAS
998  TARJETAS DE CREDITO PERSONAS NATURALES          5          AVANCES EFECT
999                     CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS

     tasaefectivaanual       montos  num_creditos_desembolsados
0                28.34    593975.00                          47
1                11.58  13679369.34                          33
2                20.40   3701160.00                           0
3                15.23   3850863.00                          50
4                30.50    243807.00                           0
..                 ...          ...                         ...
995              11.27   6676626.30                         102
996               8.61  11176820.00                           0
997              17.02    965000.00                           0
998              30.79   1702206.54                        2563
999              25.14  39049779.38                       13224

[1000 rows x 12 columns]>

In [16]:
data.shape

(1000, 12)

In [17]:
data.info

<bound method DataFrame.info of      tipoentidad  codigoentidad                        nombreentidad  \
0             32              1  Cooperativa Financiera De Antioquia
1              1              7                          Bancolombia
2              1             23                   Banco De Occidente
3              1             13                        Bbva Colombia
4              1             34                          Bansuperior
..           ...            ...                                  ...
995            1             30                    Banco Caja Social
996            1              5   Banco Cafetero S.A. En Liquidación
997            1             49                            Av Villas
998            1             14                       Helm Bank S.A.
999            1             39                     Banco Davivienda

                  fechacorte  unidad_de_captura                        nombre  \
0    2019-02-01T00:00:00.000                 11          CREDITOS COMERCIALES
1    2014-09-26T00:00:00.000                 11          CREDITOS COMERCIALES
2    2007-05-04T00:00:00.000                  9           CREDITOS DE CONSUMO
3    2013-05-03T00:00:00.000                 11          CREDITOS COMERCIALES
4    2002-05-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
..                       ...                ...                           ...
995  2021-08-27T00:00:00.000                 11          CREDITOS COMERCIALES
996  2002-11-01T00:00:00.000                 11          CREDITOS COMERCIALES
997  2003-08-15T00:00:00.000                 11          CREDITOS COMERCIALES
998  2012-08-03T00:00:00.000                 12  OTRAS MODALIDADES DE CREDITO
999  2012-12-21T00:00:00.000                  9           CREDITOS DE CONSUMO

                                       tipo  subcuenta             nombre_sub  \
0                                 ORDINARIO          5      ENTRE 1 Y 30 DIAS
1                                 ORDINARIO         40     A MAS DE 1825 DIAS
2                       CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS
3                                 ORDINARIO         20  ENTRE 366 Y 1095 DIAS
4    TARJETAS DE CREDITO PERSONAS NATURALES         40     CONS ENT 13 Y 18 M
..                                      ...        ...                    ...
995                               ORDINARIO         20  ENTRE 366 Y 1095 DIAS
996                            DE TESORERIA        110     ENTRE 15 Y 30 DIAS
997                               ORDINARIO         10    ENTRE 31 Y 365 DIAS
998  TARJETAS DE CREDITO PERSONAS NATURALES          5          AVANCES EFECT
999                     CREDITOS DE CONSUMO         20  ENTRE 366 Y 1095 DIAS

     tasaefectivaanual       montos  num_creditos_desembolsados
0                28.34    593975.00                          47
1                11.58  13679369.34                          33
2                20.40   3701160.00                           0
3                15.23   3850863.00                          50
4                30.50    243807.00                           0
..                 ...          ...                         ...
995              11.27   6676626.30                         102
996               8.61  11176820.00                           0
997              17.02    965000.00                           0
998              30.79   1702206.54                        2563
999              25.14  39049779.38                       13224

[1000 rows x 12 columns]>

In [18]:
data.sample(15)

,tipoentidad,codigoentidad,nombreentidad,fechacorte,unidad_de_captura,nombre,tipo,subcuenta,nombre_sub,tasaefectivaanual,montos,num_creditos_desembolsados
163,1,7,Bancolombia,2018-11-30T00:00:00.000,11,CREDITOS COMERCIALES,ORDINARIO,30,ENTRE 1096 Y 1825 DIAS,11.07,33256494.94,118
577,32,4,Cotrafa Financiera,2017-03-24T00:00:00.000,9,CREDITOS DE CONSUMO,CREDITOS DE CONSUMO,20,ENTRE 366 Y 1095 DIAS,18.32,630051.00,141
203,4,23,Serfinansa,2008-10-10T00:00:00.000,9,CREDITOS DE CONSUMO,CREDITOS DE CONSUMO,20,ENTRE 366 Y 1095 DIAS,29.50,586447.46,0
933,1,14,Helm Bank S.A.,2009-02-27T00:00:00.000,12,OTRAS MODALIDADES DE CREDITO,TARJETAS DE CREDITO EMPRESARIALES,60,AVANCES EFECTIVO,30.60,59688.66,0
982,32,1,Cooperativa Financiera De Antioquia,2018-12-14T00:00:00.000,11,CREDITOS COMERCIALES,ORDINARIO,40,A MAS DE 1825 DIAS,16.10,472800.00,8
640,1,42,"Banco Colpatria, ""Scotiabank""",2008-10-17T00:00:00.000,8,CREDITOS DE VIVIENDA,CREDITOS DE VIVIENDA CONSTRUCCION,5,CONSTRUCCION VIVIENDA DIF VIS (PESOS),17.70,200000.00,0
31,1,47,Conavi Banco Comercial Y De Ahorros S.A.,2004-08-06T00:00:00.000,12,OTRAS MODALIDADES DE CREDITO,TARJETAS DE CREDITO EMPRESARIALES,70,CONSUMOS 1 MES,0.00,1166073.00,0
215,1,23,Banco De Occidente,2004-01-02T00:00:00.000,12,OTRAS MODALIDADES DE CREDITO,TARJETAS DE CREDITO EMPRESARIALES,70,CONSUMOS 1 MES,29.08,69.00,0
164,1,10,Banco Gnb,2014-03-07T00:00:00.000,12,OTRAS MODALIDADES DE CREDITO,TARJETAS DE CREDITO PERSONAS NATURALES,10,CONSUMO 1 MES,0.00,1979136.27,13059
125,1,39,Banco Davivienda,2009-01-09T00:00:00.000,12,OTRAS MODALIDADES DE CREDITO,TARJETAS DE CREDITO PERSONAS NATURALES,40,CONS ENT 13 Y 18 M,30.62,865460.18,0
374,1,23,Banco De Occidente,2012-08-31T00:00:00.000,11,CREDITOS COMERCIALES,ORDINARIO,30,ENTRE 1096 Y 1825 DIAS,11.67,38680798.00,159
506,1,1,Banco De Bogota,2018-06-29T00:00:00.000,10,MICROCREDITOS,DIFERENTE DE LEASING,80,A MAS DE 1825 DIAS,31.09,140249.00,9
172,1,23,Banco De Occidente,2008-11-07T00:00:00.000,9,CREDITOS DE CONSUMO,CREDITOS DE CONSUMO,10,ENTRE 31 Y 365 DIAS,23.89,104863.00,0
671,1,13,Bbva Colombia,2007-03-30T00:00:00.000,11,CREDITOS COMERCIALES,PREFERENCIAL O CORPORATIVO,60,ENTRE 366 Y 1095 DIAS,10.99,10783000.00,0
411,32,1,Cooperativa Financiera De Antioquia,2016-08-05T00:00:00.000,9,CREDITOS DE CONSUMO,CREDITOS DE CONSUMO,20,ENTRE 366 Y 1095 DIAS,22.59,360398.00,177

In [20]:
data['fechacorte'].describe()

count                        1000
unique                        650
top       2014-01-03T00:00:00.000
freq                            5
Name: fechacorte, dtype: object